src/app/decks/DeckItem.js, src/app/decks/Decks.js, src/app/decks/HabitTracker.js, src/app/decks/SkillProgress.js, src/app/review/Review.js, src/app/utils/savedDecks.js, src/app/utils/studyProgress.js
Updates the study scheduler to set review information at the card level. This allows the scheduler (leitner.js) to determine the current progress/proficiency of that deck. Progress refers to how many cards have been seen at least once, while proficiency refers to how well someone knows that card. Proficiency is the decaying component of a card's progress.
The study data is stored in-browser using `localStorage`, which is a simple key-value store.
=> Update study scheduler

src/index.css
Using Margins to align things. 20px margin on the top without the mobile size restraint and 50px with it.
=> navbar from flex to block with a z-index. added mobile margin spacing

src/app/review/ReviewResults.js, src/index.css
Media Screen Query is set to width where the bug occurs
Added margin bottom for when buttons overlap.
=> Media query for progress review buttons on iPhone4 screen.

src/app/decks/Decks.js, src/app/decks/FeedbackForm.js, src/components/Footer.js, src/components/GoogleAnalytics.js, src/config/index.js
=> Change subscription field

package.json, public/index.html, src/app/decks/Decks.js, src/app/review/Review.js, src/app/review/ReviewHeader.js, src/app/review/ReviewResults.js, src/app/review/StudyProgress.js, src/app/review/StudyToggle.js, src/app/utils/prefs.js, src/components/GoogleAnalytics.js, src/components/Toggle.css, src/components/Toggle.js, src/index.css, src/spaced/leitner.js, src/spaced/leitner.test.js, yarn.lock
This PR creates a toggle on the review page that switches between studied all cards in a deck and only new or "expired" cards. This feature filters out any cards that the user is proficient with according to our study scheduler, which uses the leitner technique to exponentially increase time between studying.
This feature will reduce the amount of "wasted" studying 🎉.
=> Hiding familiar cards

src/app/review/Review.js
Removed when cleaning up the review page and never added back 😬 
https://github.com/nlaz/flashcards-for-developers/commit/a7646cb0777457ee3b13ab83ae2a1d1da9515869#diff-8e95f5b1f1768bb2f9bfa972ab63eb36L132
=> Hotfix: Fix review analytics

src/app/decks/HabitTracker.js, src/index.css
For all our Iphone4 friends out there
=> Revert to text above HabitTracker when screen shrinks below 480 pixels

README.md, config/env.js, config/index.js, config/paths.js, database/index.js, package.json, public/index.html, public/manifest.json, server/index.js, server/routes.js, src/app/App.js, yarn.lock
This PR updates the application to include an Express + MongoDB server. The new server-side code is located in the `/server` folder.
This PR introduces a new structure for the codebase for the server and database related code. Here is a snapshot of the new structure:
```
/config
/database
/server
/controllers
/middleware
/models
/src
```
This PR also introduces new environment variables for deploying the server code. Here are the new variables.
* `PORT` - The port on which the server will listen to requests (Default: 3000)
* `DATABASE_URI` - The uri of the database used to store data
* `SESSION_SECRET` - A secret phrase used to hash client-side tokens.
=> Setup application structure

.eslintrc.yml, package.json, src/app/App.js, src/app/apiActions.js, src/app/collections/Collections.js, src/app/decks/Decks.js, src/app/review/Review.js, src/app/review/ReviewNavigation.js, yarn.lock
Adds a collections page that pulls collection info from Airtable. The decks are linked to the collections. The `Collection` component copies a lot from `Decks` (the homepage). We could reuse code here but we will likely change the homepage in the near future so I'm thinking it's alright for now.
=> Add collections page

.gitignore, src/app/decks/Decks.js, src/app/decks/HabitTracker.js, src/app/review/ReviewHeader.js, src/components/Header.js, src/index.css
This PR updates the header to fix a wrapping issue on mobile. It also fixes some other UI issues.
=> Fix header wrapping on mobile

server/controllers/UserController.js, server/controllers/validation/users.js, server/models/User.js, server/routes.js, src/app/apiActions.js, src/app/decks/HabitTracker.js, src/app/review/Review.js, src/app/utils/studyProgress.js
This PR persists study sessions to the backend, stored under the user model when the user is authenticated.
=> Save study sessions

server/controllers/CollectionsController.js, server/models/Collection.js, server/routes.js, src/app/App.js, src/app/apiActions.js, src/app/collections/Collections.js, src/app/collections/CollectionsHome.js, src/index.css
This PR adds a homepage for viewing all collections in a single page.
=> Add collections home page

server/controllers/DecksController.js, server/controllers/UsersController.js, server/controllers/validation/decks.js, src/app/App.js, src/app/apiActions.js, src/app/collections/Collections.js, src/app/home/Home.js, src/components/Header.js, src/index.css
This PR adds a 'Saved Decks' page so you can finally access your favorite decks again in one place.
=> Add saved decks page

package.json, scripts/run_server_tests.js, server/__tests__/controllers/CardsContoller.test.js, server/__tests__/controllers/CollectionsController.test.js, server/__tests__/controllers/DecksController.test.js, server/__tests__/controllers/UserController.test.js, server/__tests__/server.test.js, yarn.lock
Just a couple smoke tests for the controllers to 1) make sure they build without issues, 2) get us started with some basic tests.
=> Add controller smoke tests

package.json, server/controllers/UsersController.js, server/controllers/validation/users.js, server/models/User.js, server/routes.js, src/app/App.js, src/app/Footer.js, src/app/Header.js, src/app/apiActions.js, src/app/auth/AuthRedirect.js, src/app/auth/LoginModal.js, src/app/auth/SignupFormModal.js, src/app/review/Review.css, src/components/GoogleAnalytics.js, src/components/Header.js, src/index.css, yarn.lock
This PR adds a login flow so if you are creating a new account, you can provide the required fields before signing up.
=> Add GitHub login flow

src/app/review/StudyToggle.js
Simply expands the tooltip area.
=> Fix tooltip on hide button

server/controllers/ProgressController.js, server/controllers/UsersController.js, server/controllers/validation/progress.js, server/controllers/validation/users.js, server/routes.js, src/app/apiActions.js, src/app/auth/SignupFormModal.js, src/app/review/Review.js, src/app/utils/localStorage.js, src/components/GoogleAnalytics.js
This PR syncs the localStorage progress to the database on a new sign up. This means someone that just signed up won't lose their progress after studying then signing up.
=> Persist progress on signup

src/app/Header.js
It's a boring black color @NickEngmann. Fight me.
=> Add signup button in header

config/index.js, package.json, server/index.js, yarn.lock
This reverts commit 13c0475748e5d181fd1cfb9fdbb8b4b4bafce436.
=> Revert "Fix www redirect (#43)"

scripts/sync_collections.js, server/models/Collection.js, src/app/collections/CollectionItem.js, src/app/home/Home.js, src/index.css
This PR updates the collection card types to be more interesting.
=> Update collection items

src/app/collections/Collections.js, src/app/home/DeckItem.js, src/app/home/Home.js, src/app/review/Review.js, src/index.css
This PR adds a _slight_ gray background for the header of some of main pages. It also moves the pinned decks to the top of the homepage.
=> Update pinned row on homepage

src/app/home/Home.js
This PR restricts the pinning actions to signed in users.
=> Fix issue with empty pinned decks

src/app/auth/LoginModal.js, src/app/home/Home.js, src/app/review/ReviewHeader.js, src/index.css
This PR adds a pinning action to the review page.
=> Add pin button to home page

src/app/review/Review.js, src/app/review/ReviewHeader.js, src/app/review/ReviewResults.js, src/index.css
This PR fixes some issues with the user interface. 🏗
=> Fix issue with study toggle

src/app/Header.js
A simple inclusion of a Twitter hashtag to track the tweets.
=> Hashtag for tweet tracking.

config/index.js, public/index.html, server/controllers/UsersController.js, src/app/Footer.js, src/pages/Pages.js
This PR adds a chat element to help capture user feedback.
=> Add chat element

src/app/home/HabitTracker.js
Fix the feature by sorting the dates that are used.
=> Fix current streak feature

package.json, server/controllers/CardsController.js, server/controllers/DecksController.js, server/controllers/validation/cards.js, server/controllers/validation/decks.js, server/models/Card.js, server/models/Deck.js, server/routes.js, src/app/App.js, src/app/Header.js, src/app/apiActions.js, src/app/auth/ReqAuth.js, src/app/decks/DecksNew.js, src/app/decks/MyDecksHome.js, src/app/home/DeckItem.js, src/app/review/AddCardsModal.js, src/app/review/CardsSection.js, src/app/review/DeleteModal.js, src/app/review/Review.js, src/app/review/ReviewHeader.js, src/app/review/ReviewResults.js, src/app/review/SettingsSection.js, src/index.css, src/index.js, src/pages/Membership.js, yarn.lock
This PR adds support for private decks. It adds to the Review page to create and delete cards and supportings editing and deleting decks.
=> Add private decks

server/controllers/SearchController.js, src/app/Footer.js, src/app/Header.js, src/app/collections/Collections.js, src/app/decks/DecksNew.js, src/app/home/DeckItem.js, src/app/home/Home.js, src/app/review/ReviewHeader.js, src/app/review/StudySection.js, src/components/GoogleAnalytics.js, src/components/SearchBar.js, src/index.css, src/pages/About.js
This PR updates the home page rows and deck items based on user testing from @NickEngmann. It also fixes an issue with not exposing the Upgrade button for logged in users.
=> Fix some UX issues

.eslintrc.yml, server/controllers/UsersController.js, server/controllers/validation/users.js, server/models/User.js, server/routes.js, server/utils/streaks.js, src/app/App.js, src/app/Header.js, src/app/apiActions.js, src/app/home/DeckItem.js, src/app/home/HabitTracker.js, src/app/home/Home.js, src/app/profile/DecksSection.js, src/app/profile/GridItem.js, src/app/profile/GridSquare.js, src/app/profile/OverviewSection.js, src/app/profile/PinnedSection.js, src/app/profile/Profile.js, src/app/profile/ReviewHeatmap.js, src/app/review/Review.js, src/app/settings/DeleteAccountModal.js, src/app/settings/Settings.js, src/app/utils/streaks.js, src/components/Emoji.js, src/components/Tab.js, src/index.css, src/pages/Membership.js
This (larger) PR creates the profile page for a user to find user-specific information, see progress, and edit decks/pins. It sets up the profile page as a container with tabs for specific things (decks). It also creates a review/activity heatmap which is going to be really cool.
=> Add profile page & edit settings page

server/controllers/UsersController.js, server/controllers/validation/users.js, src/app/auth/SignupFormModal.js, src/app/settings/Settings.js
This PR adds a username field to the sign up form so new users are required to create a username. The input is prefilled with their github username.
=> Add username to signup modal

server/controllers/DecksController.js, server/controllers/ProgressController.js, server/controllers/UsersController.js, server/controllers/validation/progress.js, server/routes.js, src/app/App.js, src/app/Header.js, src/app/apiActions.js, src/app/auth/ReqUser.js, src/app/home/Home.js, src/app/profile/DecksSection.js, src/app/profile/OverviewSection.js, src/app/profile/PinnedSection.js, src/app/profile/Profile.js, src/app/profile/ReviewHeatmap.js, src/app/settings/Settings.js
This PR supports username routes like `/nlaz` and `/nlaz/pinned`. It refactors links and endpoints to support usernames instead of user ids.
=> Support username routes

server/controllers/UsersController.js, server/routes.js, src/app/App.js, src/app/Header.js, src/app/apiActions.js, src/app/auth/ReqUser.js, src/app/auth/ReqUsername.js, src/app/home/Home.js, src/app/profile/Profile.js, src/app/settings/Settings.js, src/components/Emoji.js, src/index.css
This PR adds a modal for adding a username if it is not already chosen by the user. It will appear on any initial page load if the user is signed in.
=> Add username modal

server/controllers/DecksController.js, src/app/settings/Settings.js
This PR adds a login modal if someone is trying to view the settings page without being signed in.
=> Settings page requires logging in

src/app/review/StudyProgress.js, src/app/review/StudySection.js
After much anticipation, this PR changes the study section to support reviewing incorrect cards. To make this happen, we had to add a "page" of current cards and an array of incorrect cards.
=> Review incorrect cards

src/app/review/DeckFeedback.js, src/app/review/ReviewHeader.js
=> open new tab on a tags
